services:
  frontend:
    build: 
      context: ./frontend
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.rule=Host(`${DOMAIN}`) && PathPrefix(`/`)"
      - "traefik.http.routers.frontend.tls.certresolver=le"
      - "traefik.http.routers.frontend.tls=true"
    networks:
      - traefik
      
  backend:
    build: 
      context: ./backend
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.routers.backend.rule=Host(`${DOMAIN}`) && PathPrefix(`/backend`)"
      - "traefik.http.routers.backend.tls.certresolver=le"
      - "traefik.http.routers.backend.tls=true"
    depends_on:
      - pg_db
    networks:
      - traefik
      - pg_net

  pg_db:
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pg_net

  traefik:
    image: traefik:2.7
    restart: unless-stopped
    command:
      - "--api.insecure=false"
      - "--certificatesresolvers.le.acme.email=vkirbiatev@gmail.com"
      - "--certificatesresolvers.le.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.le.acme.httpchallenge=true"
      - "--certificatesresolvers.le.acme.storage=/le/acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.websecure.address=:443"
      - "--log.level=WARN"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=${COMPOSE_PROJECT_NAME}_traefik"
      - "--providers.docker=true"
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1::8080"
    volumes:
      - "/home/traefik/le:/le"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - traefik

volumes:
  pgdata:

networks:
  pg_net:
  traefik:

