services:
  frontend:
    build: 
      context: ./frontend
    restart: unless-stopped
    ports:
      - 4000:3000
      
  backend:
    build: 
      context: ./backend
    restart: unless-stopped
    ports:
      - 3000:3000
    depends_on:
      - pg_db
    networks:
      - pg_net

  pg_db:
    image: postgres:16
    restart: unless-stopped
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - pg_net

volumes:
  pgdata:

networks:
  pg_net:

